services:
  jj-tool-api:
    build:
      context: /home/pi/GIT/jj-tool
      dockerfile: apps/api/Dockerfile
    container_name: jj-tool-api
    restart: always
    env_file:
      - .env
    volumes:
      - /media/docker/jj-tool/data:/app/data
    networks:
      - proxy

  jj-tool-app:
    build:
      context: /home/pi/GIT/jj-tool
      dockerfile: apps/app/Dockerfile
    container_name: jj-tool-app
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
